- hosts: all
  vars:
    package: 
      - httpd
      - wget
      - tree
      - git
  tasks: 
  - name: install packages
    yum:
      name: "{{ package }}"
      state: latest


  - name: start apache
    service:
      name: httpd
      state: started


